minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: admin123456
  bucketName: shop


server:
  port: 8090

spring:
  application:
    name: file

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/