server:
  port: 8083

spring:
  application:
    name: service-orders
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
rocketmq:
  name-server: localhost:9876


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#showSql
logging:
  level:
    com:
      example:
        mapper : debug