eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: redis
    timeout: 3600s
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: localhost
    port: 6379
    timeout: 5000ms
  cloud:
    gateway:
      discovery:
        locator:
          # 启动服务注册与发现的路由
          enabled: true
          # 开启小写路由
          lowerCaseServiceId: true
#      # 跨域
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedHeaders: "*"
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - DELETE
#              - PUT
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE

logging:
  level:
    com:
      shop:
        gateway:
          mapper: debug
          dao: debug

