version: '3'

services:
  Kafka1:
    image: wurstmeister/kafka
    hostname: Kafka1
    container_name: Kafka1
    ports: 
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: Kafka1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: Zookeeper1:2181
