server:
  port: 8092

spring:
  application:
    name: msg
  data:
    mongodb:
      uri: mongodb://localhost:27017/shop

  cloud:
    stream:
      default-binder: kafka #默认的绑定器，
      kafka: #如果用的是rabbitMQ这里填 rabbit
        binder:
          brokers: #Kafka的消息中间件服务器地址
            - localhost:9092
      bindings:
        output: #通道名称
          binder: kafka
          destination: online-shop-msg #消息发往的目的地，对应topic
          group: online-shop-msg-group #对应kafka的group
          content-type: text/plain #消息的格式

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#showSql
logging:
  level:
    com:
      shop:
        goods: info

