#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


server:
  port: 8086

spring:
  application:
    name: service-email
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.qq.com
    username: 246553278@qq.com # 邮箱账号
    password: cnwdajudsnvvcacg # 授权码（下面将会告诉你怎么申请）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

rocketmq:
  name-server: localhost:9876
  producer:
    group: ordersProducer




#  session:
#    store-type: redis
#    timeout: 3600s
#    redis:
#      flush-mode: on_save
#      namespace: spring:session
#  redis:
#    host: localhost
#    port: 6379
#    timeout: 5000ms

#showSql
logging:
  level:
    com:
      example:
        mapper: debug


#        rocketmq.producer.group = producer_bank2
#        rocketmq.name-server = 127.0.0.1:9876