# 服务发现与注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# 配置中心
spring:
  cloud:
    config:
      name: zuulApplication
      profile: dev
      label: master
      discovery:
        service-id: server-config
        enabled: true


